### ISSUE TITLE
MaterialDesignDataGridTextColumnPopupEditingStyle: Mouse and focus issues

### ISSUE THREAD

**Issue by woodlandhunter** [ButchersBoy/MaterialDesignInXamlToolkit#493]
When you double click on a cell which has `EditingElementStyle="{StaticResource MaterialDesignDataGridTextColumnPopupEditingStyle}"` defined, the popup appears but there a few issues:

1) You can't move the cursor using the mouse and can't select text with the mouse (although right clicking brings up the context menu correctly).
2) If the cell editing popup is open and you change focus to another app, the popup remains on top of the other application.
3) (Minor/opinion) The cursor's position is at the beginning of the TextBox when the popup editor opens (I think this would typically be at the end?)

To reproduce:
- Open the WPF demo
- Selecting the "Grids" page using the menu
- Double click on a cell in the *Name* or *Description* columns
- Try using the left mouse button to move the cursor or select text
- Switch to another application while the cell editor is open

Here's a screenshot of the popup over another window.
![popup_example](https://cloud.githubusercontent.com/assets/6824706/18284485/bc14b9d0-742f-11e6-8c24-ee7fdd55cbb8.png)

**Comment by ButchersBoy** [comment]
Fixed parts 2 and 3.  Part 1 seems like it's going to be painful...

**Comment by husanshao53** [comment]
文件不存在，只能读不能写

**Comment by MichelMichels** [comment]
I can confirm that part 1 is still an issue. I think it's a bug in the `ControlzEx` library. I don't see an easy fix at this moment.
